// Auto-generated Z3 Constraint Polyhedron via DEX Invariants
// Witness: x = 20, y = 30 → constant-product k = x·y = 600
// The geometry is a trigonometric sweep of the bounded solution space.
// Generated by DSSS TrigCADCompiler from ZK witness (x_s=5120, y_s=7680, nBits=16, fb=8)

steps = 10;   // angular resolution (θ, φ)
xBound = 20;  // X-amplitude from witness
yBound = 30;  // Y-amplitude from witness
kBound = xBound * yBound;  // = 600, Z-amplitude

// Generate points on the swept surface
points = [
  for (i = [0 : steps-1])   // θ index
    for (j = [0 : steps-1]) // φ index
      let (
        theta = i * 2 * PI / steps,
        phi   = j * PI / steps,
        x = xBound * sin(phi) * cos(theta),
        y = yBound * sin(phi) * sin(theta),
        z = kBound * cos(phi)
      )
      [x, y, z]
];

// Generate quad faces (polyhedron splits into triangles automatically)
faces = [
  for (i = [0 : steps-2])
    for (j = [0 : steps-2])
      let (
        p1 = i * steps + j,
        p2 = p1 + 1,
        p3 = p1 + steps,
        p4 = p3 + 1
      )
      [p1, p2, p4, p3]
];

// Render
polyhedron(
  points = points,
  faces  = faces
);
